arb-dir: lib/l10n
template-arb-file: shadcn_en.arb
output-localization-file: shadcn_localizations.dart
output-class: ShadcnLocalizations
synthetic-package: false
output-dir: lib/src/components/locale
nullable-getter: false

